### PR TITLE
Add win cache

### PR DESCRIPTION
**Pull request by alexkart**
Extract `WinCache` from `yiisoft/cache`.

### CODE REVIEW

**Comment by samdark** [comment]
I guess wincache is available for Windows only so ideally it would be great to set up something like [AppVeyor](https://www.appveyor.com/) like we have for 2.0.

**Comment by alexkart** [comment]
Do you need to create a project in AppVeyor for this repository?

**Comment by samdark** [comment]
Checking...

**Comment by samdark** [comment]
Let's handle it in master.

**Comment by alexkart** [comment]
`php_wincache.dll` needs to be added to the `ext` directory also.

**Comment by samdark** [comment]
Yes, seems so :(

**Pull request merged**
